# Generated by Django 5.2.6 on 2025-12-02 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('conference', models.CharField(choices=[('EAST', 'Eastern Conference'), ('WEST', 'Western Conference')], max_length=4)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('avg_points', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('avg_rebounds', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('avg_assists', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.team')),
            ],
            options={
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('final', 'Final')], default='scheduled', max_length=20)),
                ('prediction_home_win_prob', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted probability of home team winning (0-100%)', max_digits=5, null=True)),
                ('prediction_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='Model confidence in the prediction (0-100%)', max_digits=5, null=True)),
                ('predicted_spread', models.DecimalField(blank=True, decimal_places=1, help_text='Predicted point spread (positive = home team favored)', max_digits=5, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this game on the homepage')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='core.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='core.team')),
            ],
            options={
                'ordering': ['-date', 'time'],
                'unique_together': {('date', 'home_team', 'away_team')},
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_picks', models.IntegerField(default=0)),
                ('correct_picks', models.IntegerField(default=0)),
                ('favorite_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_picks', to='core.game')),
                ('picked_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_picks', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'game')},
            },
        ),
    ]
