# Generated by Django 5.2.6 on 2025-12-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avg_points_allowed',
            field=models.DecimalField(decimal_places=1, default=110.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_points_scored',
            field=models.DecimalField(decimal_places=1, default=110.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='defensive_rating',
            field=models.DecimalField(decimal_places=1, default=110.0, help_text='Points allowed per 100 possessions', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='efg_pct',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Effective Field Goal % - (FGM + 0.5*3PM) / FGA', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='elo_rating',
            field=models.DecimalField(decimal_places=1, default=1500.0, help_text='Elo rating for win probability calculations', max_digits=7),
        ),
        migrations.AddField(
            model_name='team',
            name='ft_rate',
            field=models.DecimalField(decimal_places=3, default=0.25, help_text='Free Throw Rate - FTA / FGA', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='last_10_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last_10_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last_game_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='offensive_rating',
            field=models.DecimalField(decimal_places=1, default=110.0, help_text='Points scored per 100 possessions', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='opp_efg_pct',
            field=models.DecimalField(decimal_places=3, default=0.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='opp_ft_rate',
            field=models.DecimalField(decimal_places=3, default=0.25, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='opp_orb_pct',
            field=models.DecimalField(decimal_places=3, default=0.25, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='opp_tov_pct',
            field=models.DecimalField(decimal_places=3, default=0.13, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='orb_pct',
            field=models.DecimalField(decimal_places=3, default=0.25, help_text='Offensive Rebound % - ORB / (ORB + Opp DRB)', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='pace',
            field=models.DecimalField(decimal_places=1, default=100.0, help_text='Possessions per 48 minutes', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='tov_pct',
            field=models.DecimalField(decimal_places=3, default=0.13, help_text='Turnover % - TOV / (FGA + 0.44*FTA + TOV)', max_digits=5),
        ),
    ]
