# Generated by Django 5.2.6 on 2025-12-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_advanced_team_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_3in4',
            field=models.BooleanField(default=False, help_text='Away team 3 games in 4 nights'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_b2b',
            field=models.BooleanField(default=False, help_text='Away team on back-to-back'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_elo_pre',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='away_rest_days',
            field=models.IntegerField(default=2, help_text="Days since away team's last game"),
        ),
        migrations.AddField(
            model_name='game',
            name='away_streak_pre',
            field=models.IntegerField(default=0, help_text='Away team streak before game'),
        ),
        migrations.AddField(
            model_name='game',
            name='h2h_away_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='h2h_home_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_3in4',
            field=models.BooleanField(default=False, help_text='Home team 3 games in 4 nights'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_b2b',
            field=models.BooleanField(default=False, help_text='Home team on back-to-back'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_elo_pre',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_rest_days',
            field=models.IntegerField(default=2, help_text="Days since home team's last game"),
        ),
        migrations.AddField(
            model_name='game',
            name='home_streak_pre',
            field=models.IntegerField(default=0, help_text='Home team streak before game'),
        ),
        migrations.AddField(
            model_name='team',
            name='avg_opponent_elo',
            field=models.DecimalField(decimal_places=1, default=1500.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='team',
            name='away_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='back_to_backs_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Positive=wins, negative=losses'),
        ),
        migrations.AddField(
            model_name='team',
            name='defense_trend',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Defensive trend (negative = improving)', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='games_last_7_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='home_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='points_trend',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Scoring trend over last 10 games', max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='record_vs_above_500_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='record_vs_above_500_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='record_vs_below_500_losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='record_vs_below_500_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_3p_pct',
            field=models.DecimalField(decimal_places=3, default=0.35, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_ast',
            field=models.DecimalField(decimal_places=1, default=24.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_blk',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_drb',
            field=models.DecimalField(decimal_places=1, default=34.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_fg_pct',
            field=models.DecimalField(decimal_places=3, default=0.45, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_ft_pct',
            field=models.DecimalField(decimal_places=3, default=0.78, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_orb',
            field=models.DecimalField(decimal_places=1, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_stl',
            field=models.DecimalField(decimal_places=1, default=7.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='rolling_tov',
            field=models.DecimalField(decimal_places=1, default=14.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='team',
            name='strength_of_schedule',
            field=models.DecimalField(decimal_places=3, default=0.5, help_text='Average opponent win percentage', max_digits=5),
        ),
        migrations.CreateModel(
            name='HeadToHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(default='2025-26', max_length=10)),
                ('team1_wins', models.IntegerField(default=0)),
                ('team2_wins', models.IntegerField(default=0)),
                ('team1_points', models.IntegerField(default=0)),
                ('team2_points', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_team1', to='core.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_as_team2', to='core.team')),
            ],
            options={
                'unique_together': {('team1', 'team2', 'season')},
            },
        ),
    ]
