# Generated by Django 5.2.6 on 2025-12-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_game_away_3in4_game_away_b2b_game_away_elo_pre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='predicted_away_score',
            field=models.IntegerField(blank=True, help_text='Predicted score for away team', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='predicted_home_score',
            field=models.IntegerField(blank=True, help_text='Predicted score for home team', null=True),
        ),
    ]
