# Generated by Django 5.2.6 on 2025-12-03 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_game_predicted_away_score_game_predicted_home_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_game_id', models.IntegerField(help_text='Game ID from balldontlie API', unique=True)),
                ('date', models.DateField()),
                ('season', models.IntegerField(help_text='Season year (e.g., 2024 for 2024-25 season)')),
                ('home_team_abbr', models.CharField(max_length=5)),
                ('away_team_abbr', models.CharField(max_length=5)),
                ('home_score', models.IntegerField()),
                ('away_score', models.IntegerField()),
                ('home_win_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('away_win_pct', models.DecimalField(decimal_places=3, max_digits=5, null=True)),
                ('home_ppg_l10', models.DecimalField(decimal_places=1, help_text='Home team PPG last 10', max_digits=5, null=True)),
                ('away_ppg_l10', models.DecimalField(decimal_places=1, help_text='Away team PPG last 10', max_digits=5, null=True)),
                ('home_papg_l10', models.DecimalField(decimal_places=1, help_text='Home team Points Allowed PG last 10', max_digits=5, null=True)),
                ('away_papg_l10', models.DecimalField(decimal_places=1, help_text='Away team Points Allowed PG last 10', max_digits=5, null=True)),
                ('home_streak', models.IntegerField(default=0, help_text='Home team streak (positive=wins)')),
                ('away_streak', models.IntegerField(default=0, help_text='Away team streak (positive=wins)')),
                ('home_rest_days', models.IntegerField(default=2)),
                ('away_rest_days', models.IntegerField(default=2)),
                ('h2h_home_wins', models.IntegerField(default=0)),
                ('h2h_away_wins', models.IntegerField(default=0)),
                ('home_home_wins', models.IntegerField(default=0)),
                ('home_home_losses', models.IntegerField(default=0)),
                ('away_away_wins', models.IntegerField(default=0)),
                ('away_away_losses', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['season'], name='core_histor_season_963ce3_idx'), models.Index(fields=['date'], name='core_histor_date_643025_idx'), models.Index(fields=['home_team_abbr', 'away_team_abbr'], name='core_histor_home_te_da2c5d_idx')],
            },
        ),
    ]
