# Generated by Django 5.2.6 on 2025-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_historicalgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vegas_away_ml',
            field=models.IntegerField(blank=True, help_text='Vegas away team moneyline', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='vegas_home_ml',
            field=models.IntegerField(blank=True, help_text='Vegas home team moneyline', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='vegas_spread',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Vegas spread (positive = home team favored)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='vegas_total',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Vegas over/under total', max_digits=5, null=True),
        ),
    ]
