# Generated by Django 5.2.6 on 2025-12-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_game_vegas_away_ml_game_vegas_home_ml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpick',
            name='evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
